[package]
name = "civilis"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.12.0"
url = "2.2.2"
psl = "2"
async-recursion = "1.0.0"
futures = "0.3.21"